FROM node:8-alpine
RUN apk update

RUN apk add --update bash
RUN npm install webpack -g
RUN npm install webpack-dev-server -g

RUN npm i -g npm@5.6.0
RUN npm install -g --unsafe-perm polymer-cli
RUN npm install -g webpack-cli
RUN npm install -g typescript

WORKDIR /code